global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'pager-duty-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'alerts@example.com'
        send_resolved: true
        html: '{{ template "email.html" . }}'
        headers:
          subject: '{{ template "email.subject" . }}'

  - name: 'pager-duty-critical'
    webhook_configs:
      - url: 'https://api.pagerduty.com/v2/enqueue'
        http_config:
          basic_auth:
            username: 'pagerduty'
            password: 'pagerduty-token'
        send_resolved: true

templates:
  - '/etc/alertmanager/templates/*.tmpl'






























